version: '3.8'

services:

  # --- BANCO DE DADOS ---
  sqlserver-service:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaSenha123!"
    volumes:
      - sqlserver-data:/var/opt/mssql


  # --- BROKER DE MENSAGERIA ---
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"


  # --- MICROSSERVIÇO DE USUÁRIOS ---
  users-api:
    image: fcg-users-api:v1
    container_name: users-api-container
    build:
      context: .
      dockerfile: FCG.UsersAPI/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
      ConnectionStrings__UsuariosConnection: "Server=sqlserver-service;Database=Db_Usuarios;User Id=sa;Password=NovaSenha123!;TrustServerCertificate=True;"
    depends_on:
      - rabbitmq-service
      - sqlserver-service


  # --- MICROSSERVIÇO DE CATÁLOGO ---
  catalog-api:
    image: fcg-catalog-api:v1
    container_name: catalog-api-container
    build:
      context: .
      dockerfile: FCG.CatalogAPI/Dockerfile
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
      ConnectionStrings__CatalogConnection: "Server=sqlserver-service;Database=Db_Jogos;User Id=sa;Password=NovaSenha123!;TrustServerCertificate=True;"
    depends_on:
      - rabbitmq-service
      - sqlserver-service


  # --- MICROSSERVIÇO DE PAGAMENTOS ---
  payments-api:
    image: fcg-payments-api:v1
    container_name: payments-api-container
    build:
      context: .
      dockerfile: FCG.PaymentsAPI/Dockerfile
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
    depends_on:
      - rabbitmq-service


  # --- MICROSSERVIÇO DE NOTIFICAÇÕES ---
  notifications-api:
    image: fcg-notifications-api:v1
    container_name: notifications-api-container
    build:
      context: .
      dockerfile: FCG.NotificationsAPI/Dockerfile
    ports:
      - "8084:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
    depends_on:
      - rabbitmq-service


volumes:
  sqlserver-data: