version: '3.8'

services:

  # --- BANCOS DE DADOS ---
  sqlserver-service:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaSenha123!"
    volumes:
      - sqlserver-data:/var/opt/mssql

  mongodb-service:
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "Password123!"
    volumes:
      - mongodb-data:/data/db

  # --- CACHE DISTRIBUÍDO ---
  redis-service:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # --- BROKER DE MENSAGERIA ---
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  # --- MICROSSERVIÇO DE USUÁRIOS ---
  users-api:
    image: fcg-users-api:v1
    container_name: users-api-container
    build:
      context: .
      dockerfile: FCG.UsersAPI/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
      ConnectionStrings__UsuariosConnection: "Server=sqlserver-service;Database=Db_Usuarios;User Id=sa;Password=NovaSenha123!;TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis-service:6379"
      ConnectionStrings__MongoDb: "mongodb://root:Password123!@mongodb-service:27017"
    depends_on:
      - rabbitmq-service
      - sqlserver-service
      - redis-service
      - mongodb-service

  # --- MICROSSERVIÇO DE CATÁLOGO ---
  catalog-api:
    image: fcg-catalog-api:v1
    container_name: catalog-api-container
    build:
      context: .
      dockerfile: FCG.CatalogAPI/Dockerfile
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
      ConnectionStrings__CatalogConnection: "Server=sqlserver-service;Database=Db_Jogos;User Id=sa;Password=NovaSenha123!;TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis-service:6379"
      ConnectionStrings__MongoDb: "mongodb://root:Password123!@mongodb-service:27017"
    depends_on:
      - rabbitmq-service
      - sqlserver-service
      - redis-service
      - mongodb-service

  # --- MICROSSERVIÇO DE PAGAMENTOS ---
  payments-api:
    image: fcg-payments-api:v1
    container_name: payments-api-container
    build:
      context: .
      dockerfile: FCG.PaymentsAPI/Dockerfile
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
      ConnectionStrings__Redis: "redis-service:6379"
      ConnectionStrings__MongoDb: "mongodb://root:Password123!@mongodb-service:27017"
    depends_on:
      - rabbitmq-service
      - redis-service
      - mongodb-service

  # --- MICROSSERVIÇO DE NOTIFICAÇÕES ---
  notifications-api:
    image: fcg-notifications-api:v1
    container_name: notifications-api-container
    build:
      context: .
      dockerfile: FCG.NotificationsAPI/Dockerfile
    ports:
      - "8084:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMq__Host: rabbitmq-service
      ConnectionStrings__Redis: "redis-service:6379"
      ConnectionStrings__MongoDb: "mongodb://root:Password123!@mongodb-service:27017"
    depends_on:
      - rabbitmq-service
      - redis-service
      - mongodb-service

  # --- API GATEWAY ---
  kong:
    image: kong:3.9.0
    container_name: kong-container
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./k8s/kong/kong.yml:/kong/declarative/kong.yml:ro

  # --- OBSERVABILIDADE (PROMETHEUS & GRAFANA) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./k8s/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  sqlserver-data:
  mongodb-data:
  redis-data:
  prometheus-data:
  grafana-data: