apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
        - containerPort: 3000 # Porta interna da interface web do Grafana
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin" # Senha padrão inicial de acesso ao dashboard