apiVersion: v1
kind: Secret
metadata:
  name: kong-jwt-secret
  namespace: default
type: Opaque
stringData:
  JWT_KEY: "SuaAppJwt"
  JWT_SECRET: "L9f2QvW8xYp3Zr6TnK1M5D7GhJ0sC4B8UeRtUyVnIqXoPaSdFgHjKlZmN2bVw=="