apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: default
data:
  kong.yml.template: |
    _format_version: "3.0"
    
    services:
      - name: users-service
        url: http://users-service:80
        routes:
          # Rotas públicas (sem autenticação)
          - name: public-user-routes
            paths:
              - /auth
              - /Auth
              - /swagger
            strip_path: false

          # Rotas protegidas (exigem JWT)
          - name: protected-user-routes
            paths:
              - /api/usuario
              - /api/Usuario
            strip_path: false
            plugins:
              - name: jwt

      - name: catalog-service
        url: http://catalog-service:80
        routes:
          - name: catalog-routes
            paths:
              - /api/jogos
              - /api/Jogos
            strip_path: false
            plugins:
              - name: jwt

    plugins:
      - name: rate-limiting
        config:
          minute: 100
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
          credentials: true

    consumers:
      - username: fcg-user
        jwt_secrets:
          - key: "$JWT_KEY"
            secret: "$JWT_SECRET"
            algorithm: "HS256"